### ISSUE TITLE
Feature discussion

### ISSUE THREAD

**Issue by Lilylicious** [Lilylicious/ThaumicEquivalence#1]
This is meant for discussion of potential features of the Thaumic Equivalence mod. Things that neither Thaumcraft or ProjectE do, but the addon can do with both of them.

Examples: EMC powered staff/wand, EMC conversion of Essentia, etc.

**Comment by thrimecia** [comment]
I would like to being by saying that I was quite happy to discover this mod. Thank you, Lilylicious, for your work so far; ProjectE and Thaumcraft are probably my two favorite Minecraft mods of all time, so seeing them bridged makes me very happy.

An initial disclaimer: I play on 1.7.10, and therefore am familiar with Thaumcraft 4. I have read the change logs for Thaumcraft 5, so I have some idea of what is going on there, but I do not have in-depth knowledge. For some of my comments, I am drawing on my previous experience with Thaumcraft 3, as 5 seems to have switched certain features back to the style of 3 (such as replenishment from the aura).

I apologize if some of my comments below seem utterly obvious; no insult to anyone's experience or knowledge is intended. It is simply that, as I do not know upon what premises others are reasoning, I cannot be sure that we will communicate effectively unless the underlying assumptions are spelled out.

I think the idea of an EMC-powered staff or wand is a good one. I also think, however, that it should definitely be a toggle-able feature in the config file, as it would change the flavor of Thaumcraft in ways that some (such as myself) would find delightful, but others would not enjoy. I also might suggest an easily carried item to convert EMC to vis - perhaps a wand focus which, when equipped onto a wand, drains EMC to recharge the wand's core. Items similar to this last would be useful for cross-mod compatibility, as they would allow the EMC system to easily interface with the other Thaumcraft add-ons out there, none of which are configured to work with EMC as far as I know, but all of which work with vis and essentia. Of course, such items would again change the flavor and balance of Thaumcraft, in ways that some would like and some would not.

I suppose the most crucial feature I am really suggesting here is modularity, or the ability of the player to selectively control which features of the mod are active and which are not. Given the excellent modularity of ProjectE in general, and the two or three different modes  outlined on the project summary page (normal mode, hard mode, possibly easy mode), I imagine Lilylicious and any others involved in authoring this mod are quite probably already intending this sort of flexibility. Nonetheless, I have included below some of my thoughts about why such flexibility will benefit not only gameplay balance, but flavor as well. (If the reader is not interested, and wishes only to see other suggestions for items, etc., skip to the line break.)

ProjectE differs from many mods in that it is 'sustainable.' By this I mean that it gives the player tools which reduce time spent on maintenance, potentially all the way to zero. For example, if one is willing and able to pay for them, a large array of energy collectors will effectively produce resources for free.

Some players dislike that, but I love it. Whether 'sustainability' is a good thing or a bad thing depends on one's play style and what one enjoys about Minecraft. Personally, I don't like working frantically just to keep my base running. I don't mind having to input effort in order to build something new, but I do mind having to upkeep everything I build. Once one's base gets large enough, even low-grade maintenance tasks can stack up into an insurmountably huge chore.

For other players, however, the need to constantly gather resources is enjoyable, and pushes them to design ever-more-clever automated systems to keep up with the demand.

In short, a game is not just about what the player can do, but also what they can't. Because Minecraft is such a flexible platform, it attracts many different types of players, who have different likes and dislikes when it comes to how and to what degree their power is constrained.

Thaumcraft 4, and so far as I can tell Thaumcraft 5, are what I might call 'mildly unsustainable.' The player doesn't have to run around all the time constantly pulling in new resources, and some of the items and 'fuel sources' in Thaumcraft are effectively inexhaustible, but there are also certain resources that do require maintenance. Obtaining essentia for crafting, for example, can often require quite complicated systems to automate - when it is possible to automate at all. Most wands also run out fairly quickly, and recharging them from nodes or from the aura can deplete an area of magic.

What is the point of all this? Simply that the difficulty of obtaining certain resources within Thaumcraft is not merely a matter of gameplay balance, but of flavor. Part of what we might call the style of Thaumcraft is to build convoluted, counterintuitive devices that are fundamentally inefficient. It evokes an older, less streamlined era, when technology involved spinning wheels and bubbling liquids and hissing steam that constantly reminded you the pipe next to your head might burst open at any second. It is intriguingly complicated almost to the point of being baroque, and beautiful in its complexity.

ProjectE, on the other hand, is very streamlined, and yet has managed to be so in a way that feels (at least to me) magical rather than technological. It is elegant, and beautiful in its simplicity.

Thus, any bridge between the two is liable to pull the flavor of each away from its origin. Hence why I feel modularity is a key feature: to allow the player to choose where on the flavor spectrum they wish to play. In this way, the player who wants to power their wand from their hard-earned Klein Star Omega can do so, and enjoy limitless magical energy, while the player who wants to get the Ring of Arcana by means of endless, painful, bloody essentia distillation can also do as they please.

In other words, modularity will allow a player to either climb up the ProjectE tree and reach over to pluck the fruit of Thaumcraft, or climb up the Thaumcraft tree and reach over to seize the fruit of ProjectE, or their preferred combination of both. The optimal mod not only introduces new options, but retroactively adds value or significance to the original game; the very idea of a bridge mod is an extension of this principle, enriching both of the original mods while exploring new territory.

---

Sorry for rambling on so long; hopefully that all made sense. Other brainstorm ideas: dark and red matter wand caps. Devices that draw vis from energized nodes to produce EMC, or that output vis from an EMC source to power crafting and enchanting tables. A wearable Klein Star bauble. A way to replenish nodes or the aura from EMC, so the environmentally-friendly thaumaturge can work his craft without killing all the magic-dependent critters and plants (or being hunted down by a gang of angry wisps). Perhaps a way to cut out the middle step of transforming EMC to essentia and then providing the latter to various devices, such as a jar that produces essentia of a set type when supplied with an EMC battery. This last would undercut the utility of golems and piping, but that might be a boon for players with slower computers (or who wisely fear the inevitable golem uprising).

Since Thaumcraft now includes a strong 'eldritch' element, uses for a Primordial Pearl and void metal seem logical. I'm not sure why anyone would need something as powerful as an alloy of void metal and red matter, but perhaps something could be explored there. Thaumcraft amulets and other baubles of protection that recharge from EMC instead of vis could be useful. 

The higher damage level and generally higher power level of ProjectE items renders many Thaumcraft tools irrelevant, which is completely fine, but opens the opportunity for Thaumcraft-style items to 'catch up' with a few powerful contributions of their own. Perhaps a wand focus that does a lot of damage, or does damage in an unusual shape (such as an arc in front of the user rather than a straight line).

One of the most convenient things about Thaumcraft, come to think of it, is the easy and quick wand interface. It makes the wand something of an omnitool - just hold F and swap between combat, mining, and a host of other options. What about wand foci that replicate the effects of ProjectE tools, such as the Catalytic Lens? ProjectE has already done great at keeping the inventory uncluttered by compressing the functions of multiple items into one (e.g. Ring of Arcana). This would be yet another way to free up inventory space and maximize the utility of both ProjectE tools and the player's trusty wand/staff.

Well, I've said more than enough. I hope that these thoughts were helpful. Thank you again to Lilylicious and any and all contributors to this mod. And thanks for your time and attention.

**Comment by Lilylicious** [comment]
Closing issue due to narrowing of scope in newer versions.
